export const loginTypes = Object.freeze({
    SET_LOGIN_TOKENS: 'SET_LOGIN_TOKENS',
    SET_LOGIN_TOKENS_FAILURE: 'SET_LOGIN_TOKENS_FAILURE'
});

export const livePaneTypes = Object.freeze({
    ENABLE_LIVE_PANE: "ENABLE_LIVE_PANE",
    ENABLE_LIVE_PANE_FAILURE: "ENABLE_LIVE_PANE_FAILURE",
    SET_HIT_MODE: "SET_HIT_MODE",
    SET_HIT_MODE_FAILURE: "SET_HIT_MODE_FAILURE"
})