export const loginTypes = Object.freeze({
    SET_LOGIN_TOKENS: 'SET_LOGIN_TOKENS',
    SET_LOGIN_TOKENS_FAILURE: 'SET_LOGIN_TOKENS_FAILURE',
    SET_SESSION_LIST: 'SET_SESSION_LIST'
});

export const experimentPaneTypes = Object.freeze({
    ENABLE_LIVE_PANE: "ENABLE_LIVE_PANE",
    ENABLE_LIVE_PANE_FAILURE: "ENABLE_LIVE_PANE_FAILURE",
    SET_HIT_MODE: "SET_HIT_MODE",
    SET_HIT_MODE_FAILURE: "SET_HIT_MODE_FAILURE",
    SET_SANDBOX_MODE: "SET_SANDBOX_MODE",
    SET_SANDBOX_MODE_FAILURE: "SET_SANDBOX_MODE_FAILURE",
    SET_RETAINER_MODE: "SET_RETAINER_MODE",
    SET_RETAINER_MODE_FAILURE: "SET_RETAINER_MODE_FAILURE",
    SET_CURR_EXPERIMENT: "SET_CURR_EXPERIMENT",
    SET_CURR_EXPERIMENT_FAILURE: "SET_CURR_EXPERIMENT_FAILURE",
    ADD_EXPERIMENT_NAME: "ADD_EXPERIMENT_NAME",
    ADD_EXPERIMENT_NAME_FAILURE: "ADD_EXPERIMENT_NAME_FAILURE",
    REMOVE_EXPERIMENT_NAME: "REMOVE_EXPERIMENT_NAME",
    REMOVE_EXPERIMENT_NAME_FAILURE: "REMOVE_EXPERIMENT_NAME_FAILURE"
});